--- #### #######################################################################
--- ####                POPULATE ACL
--- #### #######################################################################

-- Default Roles
INSERT INTO ACL_ROLES (NAME, DELETEABLE, DESCRIPTION) VALUES ('Guest', false, 'Default Role for all new Users.');
INSERT INTO ACL_ROLES (NAME, DELETEABLE, DESCRIPTION) VALUES ('User', false, 'After a simple validation process of an existing EMail address.');
INSERT INTO ACL_ROLES (NAME, DELETEABLE, DESCRIPTION) VALUES ('Moderator', true, 'Higher privileged role than a standard user.');
INSERT INTO ACL_ROLES (NAME, DELETEABLE, DESCRIPTION) VALUES ('Administrator', false, 'Full privilege.');

-- Admin Account
INSERT INTO ACL_ACCOUNT (EMAIL, PASSWORD, ROLE_NAME, DEFAULT_LOCALE, DEFAULT_TIMEZONE, REGISTERED, VERIFIED, DEACTIVATED, VERIFICATION_CODE)
    VALUES ('admin@sample.org', '', 'Administrator', 'EN_en', 'UTC+00:00', '1984-04-01 12:00:01.0', '2020-12-31 12:00:01.0', '2021-01-11 12:00:01.0', '03a057d0-6ee7-43b1-ac68-d9a7681165a4');
INSERT INTO ACL_ACCOUNT (EMAIL, PASSWORD, ROLE_NAME, DEFAULT_LOCALE, DEFAULT_TIMEZONE, REGISTERED, VERIFIED, DEACTIVATED, VERIFICATION_CODE)
     VALUES ('moderator@sample.org', '', 'Moderator', 'EN_en', 'UTC+00:00', '1984-04-01 12:00:01.0', '2020-12-31 12:00:01.0', '2021-01-11 12:00:01.0', '22a057d0-6756-43b1-ac68-d9a7681165a4');

-- RESOURCE
INSERT INTO ACL_RESOURCES (RESOURCE, TEMPLATE, DELETEABLE) VALUES ('ACL', 'account', false);
INSERT INTO ACL_RESOURCES (RESOURCE, TEMPLATE, DELETEABLE) VALUES ('ACL', 'login', false);
INSERT INTO ACL_RESOURCES (RESOURCE, TEMPLATE, DELETEABLE) VALUES ('ACL', 'role', false);
INSERT INTO ACL_RESOURCES (RESOURCE, TEMPLATE, DELETEABLE) VALUES ('ACL', 'resource', false);
INSERT INTO ACL_RESOURCES (RESOURCE, TEMPLATE, DELETEABLE) VALUES ('ACL', 'permission', false);

-- PERMISSION
INSERT INTO ACL_PERMISSIONS (IDX, ROLE_NAME, RESOURCE_RESOURCE, RESOURCE_TEMPLATE, DO_READ, DO_CHANGE, DO_CREATE, DO_DELETE)
    VALUES ('1f4c2b42-4408-4f99-b1aa-25002b85ea87', 'Administrator', 'ACL', 'role', true, true, true, true);
INSERT INTO ACL_PERMISSIONS (IDX, ROLE_NAME, RESOURCE_RESOURCE, RESOURCE_TEMPLATE, DO_READ, DO_CHANGE, DO_CREATE, DO_DELETE)
    VALUES ('eb7bb730-95a0-42ac-983c-258b7a56f1f4', 'Administrator', 'ACL', 'resource', true, true, true, true);
INSERT INTO ACL_PERMISSIONS (IDX, ROLE_NAME, RESOURCE_RESOURCE, RESOURCE_TEMPLATE, DO_READ, DO_CHANGE, DO_CREATE, DO_DELETE)
    VALUES ('eb7bb730-95a0-43ac-983c-258b7a56f1f4', 'Administrator', 'ACL', 'permission', true, true, true, true);
INSERT INTO ACL_PERMISSIONS (IDX, ROLE_NAME, RESOURCE_RESOURCE, RESOURCE_TEMPLATE, DO_READ, DO_CHANGE, DO_CREATE, DO_DELETE)
    VALUES ('eb7bb730-95a0-44ac-983c-258b7a56f1f4', 'Administrator', 'ACL', 'account', true, true, true, true);
INSERT INTO ACL_PERMISSIONS (IDX, ROLE_NAME, RESOURCE_RESOURCE, RESOURCE_TEMPLATE, DO_READ, DO_CHANGE, DO_CREATE, DO_DELETE)
    VALUES ('eb7bb730-95a0-45ac-983c-258b7a56f1f4', 'Administrator', 'ACL', 'login', true, false, true, false);

INSERT INTO ACL_PERMISSIONS (IDX, ROLE_NAME, RESOURCE_RESOURCE, RESOURCE_TEMPLATE, DO_READ, DO_CHANGE, DO_CREATE, DO_DELETE)
    VALUES ('zb7bbx31-95a0-45ac-983c-258b7a56f1g1', 'Moderator', 'ACL', 'role', true, false, true, false);